name: primera_app
description: "A new Flutter project."
publish_to: 'none'

# 🚀 ACTUALIZADO: Subimos a la v1.0.8+1 para el empaquetado del logotipo personalizado
version: 1.1.4+3

environment:
  sdk: '>=3.0.0 <4.0.0' # 🚀 CORREGIDO: Rango altamente compatible para que no te marque error de SDK

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  ota_update: ^7.1.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 🚀 NUEVO: Agregamos el paquete generador de iconos aquí en modo desarrollo
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # 🚀 NUEVO: Activamos la lectura de la carpeta assets de tu proyecto para que Flutter reconozca el logotipo
  assets:
    - assets/icon/water-app.png

# 🚀 NUEVO: Bloque de configuración independiente para los Launcher Icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/water-app.png"
  min_sdk_android: 21